name: Python/Flask Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout current code
      - uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Optional) Run tests, lint, etc.

      # 4) Archive the repo content (minus venv, if present)
      - name: Create ZIP
        run: zip -r app.zip . -x "**/venv/**"

      # 5) Upload artifact so it can be retrieved by next steps
      - uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      # 1) Download artifact
      - uses: actions/download-artifact@v4
        with:
          name: app-package

      # 2) Unzip
      - name: Unzip
        run: unzip app.zip

      # 3) Azure CLI Login
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4) Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "awesome-sentiment-app"  # must match your Web App name
          package: "./app.zip"
